name: Build Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: "45 0 * * 5" # Every Friday at 00:45 UTC

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest commit SHA
        id: latest_sha
        run: echo "sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/nickbonet/weekly_meal_planner_bot:latest, ghcr.io/nickbonet/weekly_meal_planner_bot:${{ steps.latest_sha.outputs.sha }}

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ghcr.io/nickbonet/weekly_meal_planner_bot:latest
          format: "table"
          exit-code: "1"
          severity: "HIGH,CRITICAL"
          ignore-unfixed: true
          vuln-type: "os,library"
          ignore-policy: ".trivyignore"
